//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int UyeID { get; set; }
        public string UyeAdi { get; set; }
        public string UyeSoyAdi { get; set; }
        public string UyeMailAdresi { get; set; }
        public string UyeSifre { get; set; }
        public string UyeNickName { get; set; }
        public string Role { get; set; }
    }
}
