//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumID { get; set; }
        public int MakaleID { get; set; }
        public string YorumYazanAdiSoyadi { get; set; }
        public string YorumAciklama { get; set; }
        public System.DateTime YorumEklenmeTarihi { get; set; }
    
        public virtual Makaleler Makaleler { get; set; }
    }
}
